### ISSUE TITLE
index out of bounds, how do i fix this? 

### ISSUE THREAD

**Issue by JuanERombado** [maxpolaczuk/RapML#1]
(tensorflow_p36) [ec2-user@ip-172-31-35-80 RapML-master]$ python3 model.py
11300
show 3 inputs
Traceback (most recent call last):
  File "model.py", line 50, in <module>
    inputs.append(embed_and_pad(inps.ix[i,:]))
  File "model.py", line 36, in embed_and_pad
    tmp[i+padding,int(row[i])] = 1
IndexError: index 11303 is out of bounds for axis 1 with size 11300

thanks

**Comment by billogbika** [comment]
hey! its because vocab.ix function is deprecated and your vocab file has the ID column twice!

**Comment by billogbika** [comment]
solution is using iloc
